// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEAYHYnoEil4N4c85yfWJmbqi_UCpDAZY',
    appId: '1:760231479897:android:5d0db861f23c964175bf48',
    messagingSenderId: '760231479897',
    projectId: 'resto-kigali',
    storageBucket: 'resto-kigali.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRd8GGmoqZk1HKWzDhdX9rXc1g5k2faHA',
    appId: '1:760231479897:ios:21d6fbb9ffefc08975bf48',
    messagingSenderId: '760231479897',
    projectId: 'resto-kigali',
    storageBucket: 'resto-kigali.firebasestorage.app',
    iosBundleId: 'com.example.restoKigali',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6C6iKo7PKzm_NJaafj7LnAKD5o5kYzMw',
    appId: '1:760231479897:web:ecd924666f00374f75bf48',
    messagingSenderId: '760231479897',
    projectId: 'resto-kigali',
    storageBucket: 'resto-kigali.firebasestorage.app',
  );
}
